# <center>Introduction to Numerical_Python</center>

#### Instalation
#### jupyter---> !pip install numpy
#### local machine ---> %pip3 install numpy
#### goggle colab ---> already installed

In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:

list1 = [1,3,4,23,2]
print(list1)

import numpy as np

arr = np.array(list1)
print(arr)


[1, 3, 4, 23, 2]
[ 1  3  4 23  2]


# 1D array


In [7]:

list1 = [1,3,4,23,2]
arr = np.array(list1)
print(arr)

[ 1  3  4 23  2]


# 2D array

In [8]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Identity matrix
### eye(size)

In [9]:
identity_mat = np.eye(5)
print(identity_mat)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# Creating arrays from python list/tuples
### array() function
### default values --> zeros function -->np.zeros(shape)
### default 1 values --> ones function ...tuples np.ones((2,3))
### full function---> specific value--->((shape),value)

In [10]:
# array function ---> array()
arr2 = np.array(list1)
print(arr2)

[ 1  3  4 23  2]


In [11]:
# default values
# np.zeros(shape)   // 1d-->(3) 2d--> (3,3)
zeros_array = np.zeros(2)
print(zeros_array)

[0. 0.]


In [12]:
#ones funtion
ones_array = np.ones((2,3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
#full function
filled_array = np.full(3,7)
filled_array2 = np.full((3,2),8)
print(filled_array)
print(filled_array2)

[7 7 7]
[[8 8]
 [8 8]
 [8 8]]


## Creating sequence of numbers in numpy
### arange function---> arrange(start,stop,step)

In [14]:
arr = np.arange(1,10,2)
print(arr)

[1 3 5 7 9]
