# <center><b>Proprties</b></center>

In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
list3 = [[23,32,23,34],
         [45,45,36,31]]
list4 = [[1.1,2],
         [5,6.3],
         [7,9]]
list5 = [
    [[1,2],[5,6],[7,9]],
    [[4,4],[1,4],[5,6]]
    ]
arr1 = np.array(list1)
arr2 = np.array(list2)
arr1_2d = np.array(list3)
arr2_2d = np.array(list4)
arr_3d = np.array(list5)

### <center><p style=color:red> shape , size , dimension , type</p></center>


In [ ]:
# shape (rows,columns)
print(arr1.shape) ## 
print(arr1_2d.shape)
print(arr2_2d.shape)
print(arr_3d.shape) # row col depth

(5,)
(2, 4)
(3, 2)
(2, 3, 2)


In [4]:
# size
print(arr1.size)

print(arr2_2d.size)

5
6


In [5]:
# number of dimentions
print(arr1.ndim)
print(arr1_2d.ndim)
print(arr_3d.ndim)

1
2
3


In [6]:
# type
print(arr1.dtype)
print(arr2_2d.dtype)

int64
float64


In [ ]:
# datatype conversion
print(arr1.astype(float)) # just a copy of orginal arr
print(arr1)
floatarr1 = arr1.astype(float)
print(floatarr1)

[1. 2. 3. 4. 5.]
[1 2 3 4 5]
[1. 2. 3. 4. 5.]
