# <center>Operator & Aggregation function</center>

In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
list3 = [[23,32,23,34],
         [45,45,36,31]]
list4 = [[1.1,2],
         [5,6.3],
         [7,9]]
list5 = [
    [[1,2],[5,6],[7,9]],
    [[4,4],[1,4],[5,6]]
    ]
arr1 = np.array(list1)
arr2 = np.array(list2)
arr1_2d = np.array(list3)
arr2_2d = np.array(list4)
arr_3d = np.array(list5)

In [4]:
# operators are same as any language
# but you can directly manupulte values without a loop
print(arr1)
print(arr1 + 5)
print(arr1 ** 2) #exponential

[1 2 3 4 5]
[ 6  7  8  9 10]
[ 1  4  9 16 25]


## <center>Some Aggregation functions</center>

In [ ]:
print(np.sum(arr1))
print(np.mean(arr1))
print(np.min(arr1))
print(np.max(arr1))
print(np.std(arr1)) #standard deviation
print(np.var(arr1)) #variance

15
3.0
1
5
1.4142135623730951
2.0
