# <center><p style=color:magenta>Indexing and Slicing</p></center>

In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np
list1 = [1,2,3,4,5,6]
list2 = [6,7,8,9,10]
list3 = [[23,32,23,34],
         [45,45,36,31]]
list4 = [[1.1,2],
         [5,6.3],
         [7,9]]
list5 = [
    [[1,2],[5,6],[7,9]],
    [[4,11],[10,3],[8,12]]
    ]
arr1 = np.array(list1)
arr2 = np.array(list2)
arr1_2d = np.array(list3)
arr2_2d = np.array(list4)
arr_3d = np.array(list5)

## <center><p style=color:red>Indexing<p></center>

In [3]:
# indexing---> 0 based index
#1d arr[pos]
#2d arr[row,col]
print(arr1[3])
print(arr1_2d[1,2])
print(arr1[-1]) #last element
print(arr1[-2]) #second last element
print(arr_3d[0,2,1]) #depth,row,col

4
36
6
5
9


## <center><p style=color:red>Slicing<p></center>

In [4]:
# arr[start:end:step]
# arr[start:end] default step 1
# arr[::]
# 0 based index
# end is always excluded
# [1,2,3,4,5]
print(arr1[1:5]) 
print(arr1[0:4])
print(arr1[:5]) # start to end
print(arr1[::]) # start to end
print(arr1[0:4:1]) # start end step
print(arr1[0:5:2])
print(arr1[-1:])
print(arr1[::-1]) #reverse


[2 3 4 5]
[1 2 3 4]
[1 2 3 4 5]
[1 2 3 4 5 6]
[1 2 3 4]
[1 3 5]
[6]
[6 5 4 3 2 1]


## <center><p style=color:red>fancy indexing<p></center>
### selecting multiple element at once

In [5]:
print(arr1[[0,2,4]]) # we will pass idx as list
# just a copy of orginal arr
arr= arr1[[0,2,4]]
print(arr)

[1 3 5]
[1 3 5]


## <center><p style=color:red>Boolean masking or filtering<p></center>
### selecting values based on condition

In [6]:
print(arr1[arr1 < 3])
print(arr1[arr1 % 2])
print(arr1[(arr1 % 2) == 0])

[1 2]
[2 1 2 1 2 1]
[2 4 6]


## <center><p style=color:red>Reshaping<p></center>
### 1d--->2d
### reshapre(row,col)
### we can only reshape when dimension matches row=col

In [7]:
reshp_arr = arr1.reshape(2,3)
print(reshp_arr)
print(arr1)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


## <center><p style=color:red>Flatning array<p></center>
#### multidimention-----> 1d array
#### ravel()
#### flatten()

In [8]:
ravel_arr = arr1_2d.ravel()
flatten_arr = arr1_2d.flatten()
print(ravel_arr)
print(flatten_arr)
print(arr1_2d)

[23 32 23 34 45 45 36 31]
[23 32 23 34 45 45 36 31]
[[23 32 23 34]
 [45 45 36 31]]
