# <center>Adding , removing , Stacking , Spiliting</center>

In [55]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [56]:
import numpy as np
list1 = [1,2,3]
list2 = [4,5,6]
list3 = [[23,32,23,34],
         [45,45,36,31]]
list5 = [
    [[1,2],[5,6],[7,9]],
    [[4,11],[10,3],[8,12]]
    ]
arr1 = np.array(list1)
arr2 = np.array(list2)
arr1_2d = np.array(list3)
arr_3d = np.array(list5)

## <center><p style=color:red>Adding<p></center>
### insert(), append(), concat()

In [57]:
# insert
# np.insert(array,index,value,axis=None)
# axis=None 1d arr
# axis=0, row-wise 
# axis=1 , col-wise
# original arr doesn't change
arr_ins = np.insert(arr1,1,10)  # arr_ins = np.insert(arr1,1,10,axis = None)
print(arr_ins)
print(arr1)

print()

arr2d_ins1 = np.insert(arr1_2d,1,10,axis = 0)
arr2d_ins2 = np.insert(arr1_2d,1,11,axis = 1)
print(arr2d_ins1)
print()
print(arr2d_ins2)

print()

arr2d_ins3 = np.insert(arr1_2d,1,[0,1],axis = 1)
print(arr2d_ins3)

[ 1 10  2  3]
[1 2 3]

[[23 32 23 34]
 [10 10 10 10]
 [45 45 36 31]]

[[23 11 32 23 34]
 [45 11 45 36 31]]

[[23  0 32 23 34]
 [45  1 45 36 31]]


In [58]:
# append
# add at the end of arr
# no change to orginal array
arr1_append1 = np.append(arr1,4)
arr1_append2 = np.append(arr1,[4,5,6])

print(arr1_append1)
print()
print(arr1_append2)

[1 2 3 4]

[1 2 3 4 5 6]


In [59]:
# concat
# np.concatenate((arr1,arr2),axis=None)
# axis = 0 row(vertical) ,axis = 1 col(horizontal)
# pass as a tupple
arr_concat1 = np.concat((arr1,arr2))
arr_concat2 = np.concat((arr1_2d,[[1,2,3],[1,2,3]]),axis=1) #arr_concat2 = np.concat((arr1_2d,arr1_2d),axis=1)
print(arr_concat1)
print(arr_concat2)

[1 2 3 4 5 6]
[[23 32 23 34  1  2  3]
 [45 45 36 31  1  2  3]]


## <center><p style=color:red>removing<p></center>
### delete()

In [60]:
# np.delete(arr,index,axis = None)
# no change to orginal array
# axis row 0 , col 1
arr1_del = np.delete(arr1,1)
print(arr1_del)

arr1_2d_del = np.delete(arr1_2d,0,axis=0) #arr,row ind,axis = row
print(arr1_2d_del)

[1 3]
[[45 45 36 31]]


## <center><p style=color:red>Stacking<p></center>
### np.vstack() , np.hstack()

In [61]:
#vertical stack,horizontal stack
arr_vstack = np.vstack((arr1,arr2))
arr_hstack = np.hstack((arr1,arr2))
print(arr_vstack,arr_hstack)

[[1 2 3]
 [4 5 6]] [1 2 3 4 5 6]


## <center><p style=color:red>spliting<p></center>
### np.spilit(arr,parts), np.hspilit() , np.vspilit()

In [62]:
arr6 = np.array([1, 2, 3, 4])
# equal split
print(np.split(arr6, 2))


"""
parts = np.split(arr6, 2)
part1 , part2 = parts
print(part1,part2)
"""

[array([1, 2]), array([3, 4])]


'\nparts = np.split(arr6, 2)\npart1 , part2 = parts\nprint(part1,part2)\n'

In [63]:
# correct split functions are np.split, np.hsplit, np.vsplit
arr_hsplits = np.hsplit(arr1_2d, 2)
arr_vsplits = np.vsplit(arr1_2d, 2)

print(arr_hsplits)
print("\n",arr_vsplits)


[array([[23, 32],
       [45, 45]]), array([[23, 34],
       [36, 31]])]

 [array([[23, 32, 23, 34]]), array([[45, 45, 36, 31]])]
