# <center>Broadcasting and Vectorisation</center>

In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np
list1 = [1,2,3]
list2 = [4,5,6]
list3 = [[23,32,23],
         [45,45,36]]
list5 = [
    [[1,2],[5,6],[7,9]],
    [[4,11],[10,3],[8,12]]
    ]
arr1 = np.array(list1)
arr2 = np.array(list2)
arr1_2d = np.array(list3)
arr_3d = np.array(list5)

<p style=color:red>Broadcasting</p> in NumPy is a powerful mechanism that allows you to perform arithmetic operations (like addition, subtraction, and multiplication) on arrays with different shapes. Instead of using explicit loops to duplicate data, NumPy virtually expands the smaller array to match the larger array's shape for fast, element-wise computation.
<p style=color:red> It conceptually "stretches" the smaller array to match the shape of the larger array so element-wise operations can occur.</p>

In [3]:
#with single value
result = arr1 + 10
print(result)

# equal dimension

result2 = arr1 + arr2
print(result2)

result3 = arr1_2d + arr1  #dimension matches
print(result3)

# if dimension doesnt matches it will arise an error

[11 12 13]
[5 7 9]
[[24 34 26]
 [46 47 39]]


In NumPy, <p style=color:red>vectorization</p> is the process of performing mathematical operations on entire arrays at once rather than using explicit for loops to iterate through individual elements
<p style=color:red>It allows an operation to be applied to an entire array at once rather than one element at a time in Python.</p>

In [4]:
result = arr1 * 10
print(result)

[10 20 30]


### <center><p style=color:red>Handle missing value and infinte</p></center>

In [11]:
# isnan() --> finds missing and returns true or false
arr = np.array([1,2,3,np.nan,4,5])
print(np.isnan(arr))  #nan is not compareable

# replace the missing value
# np.nan_to_num(array,nan=value) default 0
print(np.nan_to_num(arr,nan=100))


[False False False  True False False]
[  1.   2.   3. 100.   4.   5.]


In [14]:
inf_arr = np.array([1,2,3,np.inf,4,5,-np.inf])
print(np.isinf(inf_arr))

# replace inf to num
print(np.nan_to_num(inf_arr,posinf=20,neginf=100))

[False False False  True False False  True]
[  1.   2.   3.  20.   4.   5. 100.]
