# <center> Universal function </center>

In [32]:
import numpy as np

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]

In [33]:
# add function
z = np.add(x, y)
print(z)

[ 5  7  9 11]


### How To Create Your Own ufunc
To create your own ufunc, you have to define a function, like you do with normal functions in Python, then you add it to your NumPy ufunc library with the frompyfunc() method.

The frompyfunc() method takes the following arguments:

function - the name of the function.  
 inputs - the number of input arguments (arrays).  
 outputs - the number of output arrays.

In [34]:
def adding(x , y):
    return x+y
adding = np.frompyfunc(adding,2,1) ## (func,inputs_no,outputs_no)

print(adding([1,2,3],[4,5,6]))

[5 7 9]


In [35]:
#Check if a Function is a ufunc
#If it is not a ufunc, it will return another type, like this built-in NumPy function for joining two or more arrays:
print(type(np.add))
print(type(np.concatenate))
print(type(np.where))

<class 'numpy.ufunc'>
<class 'numpy._ArrayFunctionDispatcher'>
<class 'numpy._ArrayFunctionDispatcher'>


## Simple Arithmetic 

In [36]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

sum_arr = np.add(arr1,arr2)
subt_arr = np.subtract(arr1,arr2)
mul_arr = np.multiply(arr1,arr2)
div_arr = np.divide(arr1,arr2)
power_arr = np.power(arr1,arr2)
mod_arr = np.mod(arr1,arr2) # np.remainder(arr1,arr2)
divmod_arr = np.divmod(arr1,arr2)
abs_arr = np.absolute(arr1)

print(sum_arr,subt_arr,mul_arr,div_arr,power_arr,mod_arr,"\n",divmod_arr,"\n",abs_arr)

"""
The example above for divmod will return:
(array([3, 2, 3, 5, 25, 1]), array([1, 6, 3, 0, 0, 27]))
The first array represents the quotients, (the integer value when you divide 10 with 3, 20 with 7, 30 with 9 etc.
The second array represents the remainders of the same divisions
"""



[13 27 39 48 52 93] [ 7 13 21 32 48 27] [  30  140  270  320  100 1980] [ 3.33333333  2.85714286  3.33333333  5.         25.          1.81818182] [          1000     1280000000 19683000000000  6553600000000
           2500              0] [ 1  6  3  0  0 27] 
 (array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27])) 
 [10 20 30 40 50 60]


'\nThe example above for divmod will return:\n(array([3, 2, 3, 5, 25, 1]), array([1, 6, 3, 0, 0, 27]))\nThe first array represents the quotients, (the integer value when you divide 10 with 3, 20 with 7, 30 with 9 etc.\nThe second array represents the remainders of the same divisions\n'

# Rounding Decimals
truncation 
fix 
rounding 
floor 
ceil 

In [37]:
import numpy as np
arr = np.array([-3.1666, 3.6667])
#truncing
print(np.trunc([-3.1666, 3.6667]))

#fix
print(np.fix(arr))

#rounding
print(np.round(arr)) # >.5 ceil, .5< floor

#arround
print(np.around(arr,2)) #round to 2 decimal points

# ceil & floor
print(np.ceil(arr),np.floor(arr))



[-3.  3.]
[-3.  3.]
[-3.  4.]
[-3.17  3.67]
[-3.  4.] [-4.  3.]


# Logs


In [38]:
import numpy as np
arr = np.arange(1, 10) # 1---9

print(np.log2(arr)) # base 2
print(np.log10(arr)) # base 10
print(np.log(arr)) # base e/ natural log

# learn log at any base by creating a new function

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


# <center>Sumations</center>

In [39]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

In [40]:
arr3 = np.add(arr1, arr2)
res = np.sum([arr1, arr2])
arr5 = np.sum([arr1, arr2], axis=1)
arr6 = np.cumsum(arr) #The partial sum of [1, 2, 3, 4] would be [1, 1+2, 1+2+3, 1+2+3+4] = [1, 3, 6, 10].

print(arr3,res,arr5,arr6)


[2 4 6] 12 [6 6] [ 1  3  6 10 15 21 28 36 45]
